{% set version = "1.1.0" %}

package:
  name: nasvar
  version: {{ version }}

source:
  git_url: https://github.com/jwanglab/nasvar.git
  git_rev: eb285440957124d1d3c65aee0ba0aa291726313a

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - nasvar --version
    - aggregate --help

about:
  home: https://github.com/jwanglab/nasvar
  summary: "Variant caller for tumor-only long-read (Oxford Nanopore) sequencing"
  license: LicenseRef-UNC-NonCommercial
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - drosofff
